### ISSUE TITLE
Some LaTeX is not rendered correctly

### ISSUE THREAD

**Issue by betatim** [rgbkrk/gistexec#9]
http://lambdaops.com/gistexec/?gistID=54ef92537aaa7322c4de

some of the LaTeX is not rendered properly. Potentially wrong kind of MathJax?

**Comment by rgbkrk** [comment]
This is the config I use:

``` JavaScript
  //Init MathJax
  MathJax.Hub.Config({
      tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"] ],
          displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
          processEscapes: true,
          processEnvironments: true
      },
      // Center justify equations in code and markdown cells. Elsewhere
      // we use CSS to left justify single line equations in code cells.
      displayAlign: 'center',
      "HTML-CSS": {
          availableFonts: [],
          imageFont: null,
          preferredFont: null,
          webFont: "STIX-Web",
          //styles: {'.MathJax_Display': {"margin": 0}},
          linebreaks: { automatic: true }
      }
  });
  MathJax.Hub.Configured();
```

**Comment by rgbkrk** [comment]
I come from the future. We need to migrate some MathJax.

![image](https://github.com/rgbkrk/gistexec/assets/836375/a5f89098-0a69-4884-a4e7-cf970e6184e8)


```
 WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
replaceScript @ cdn.mathjax.org/math…MS-MML_HTMLorMML:32
gistexec.js:291 Uncaught ReferenceError: MathJax is not defined
    at gistexec (gistexec.js:291:3)
    at HTMLDocument.<anonymous> (?gistID=8639207f3401552553e8:118:21)
    at c (jquery.min.js:3:7857)
    at Object.fireWith [as resolveWith] (jquery.min.js:3:8658)
    at Function.ready (jquery.min.js:3:3266)
    at HTMLDocument.H (jquery.min.js:3:695)
```
